apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: hello-pipeline-run
spec:
  serviceAccountName: app-builder
  pipelineRef:
    name: hello-pipeline
  workspaces:
    - name: shared-workspace
      persistentvolumeclaim:
        claimName: buildpacks-source-pvc
  resources:
    - name: build-image
      resourceRef:
        name: buildpacks-app-image
  podTemplate:
    volumes:
      - name: buildpacks-cache
        persistentVolumeClaim:
          claimName: buildpacks-cache-pvc
